AllCops:
  Exclude:
    - 'test/**/*'
    - '.wgit.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'test/helpers/database_test_data.rb'
Style/ClassVars:
  Exclude:
    - 'test/helpers/database_helper.rb'
Layout/HashAlignment:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Security/Eval:
  Exclude:
    - 'bin/wgit'
Style/GuardClause:
  Exclude:
    - 'wgit.gemspec'
Metrics/BlockLength:
  Exclude:
    - '.toys.rb'
