AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'bin/**'
Security/Eval:
  Exclude:
    - 'bin/wgit'
Metrics/ParameterLists:
  Exclude:
    - 'lib/wgit/dsl.rb'
    - 'lib/wgit/database/database.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 12
Layout/LineLength:
  Max: 85
