dist: xenial
services: docker
addons:
    chrome: stable
language: ruby
rvm:
    - 3.1
    - 3.2
    - 3.3
cache: bundler
before_script: bundle exec toys db start
script: bundle exec toys ci
after_success: bundle exec toys generate_rubydocs
