dist: xenial
services: docker
addons:
    chrome: stable
language: ruby
rvm:
    - 2.5
    - 2.6
    - 2.7
cache: bundler
before_script: bundle exec toys db start
script: bundle exec toys ci
after_success: bundle exec toys generate_rubydocs
