require_relative 'wgit/version'
require_relative 'wgit/logger'
require_relative 'wgit/assertable'
require_relative 'wgit/utils'
require_relative 'wgit/url'
require_relative 'wgit/document'
require_relative 'wgit/crawler'
require_relative 'wgit/database/connection_details'
require_relative 'wgit/database/model'
require_relative 'wgit/database/database'
require_relative 'wgit/indexer'
#require_relative 'wgit/core_ext' - Must be explicitly required.
