name: RubyDocs

on:
  push:
    branches:
      - master

jobs:
  generate-rubydocs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: docs
        run: bundle exec toys generate_rubydocs
